version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.1

workflows:
  version: 2
  # The main workflow responsible for triggering all other workflows
  # in which changes are detected.
  ci:
    jobs:
      - trigger-workflows
