version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.3

workflows:
  version: 2
  ci-stg:
    when:
      equal: [master, <<pipeline.git.branch>>]
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          mapping: |
            packages/api/.* run-build-api-job true
            packages/app/.* run-build-app-job true
            packages/auth/.* run-build-auth-job true
            packages/gateway/.* run-build-gateway-job true
          base-revision: master
          config-path: .circleci/continue_config.yml
  ci-prod:
    when:
      equal: [release, <<pipeline.git.branch>>]
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          mapping: |
            packages/api/.* run-build-api-job true
            packages/app/.* run-build-app-job true
            packages/auth/.* run-build-auth-job true
            packages/gateway/.* run-build-gateway-job true
          base-revision: release
          config-path: .circleci/continue_config.yml
