version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.1

workflows:
  version: 2
  # The main workflow responsible for triggering all other workflows
  # in which changes are detected.
  ci:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          mapping: |
            api/.* run-build-api-job true
            app/.* run-build-app-job true
            auth/.* run-build-auth-job true
            gateway/.* run-build-gateway-job true
          base-revision: master
          config-path: .circleci/continue_config.yml
