version: 2.1

parameters:
  # This parameter is used to trigger the main workflow
  trigger:
    type: boolean
    default: true

  # A parameter per package
  run-build-api-job:
    type: boolean
    default: false
  run-build-app-job:
    type: boolean
    default: false
  run-build-auth-job:
    type: boolean
    default: false
  run-build-gateway-job:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: circleci/node

jobs:
  build:
    parameters:
      package_name:
        type: string

    executor: node
    working_directory: ~/project/packages/<< parameters.package_name >>

    steps:
      - checkout:
          path: ~/project
      # This step is added only to show that we are in the package directory
      - run:
          name: Content
          command: |
            cat README.md 
            echo "<< parameters.package_name >> built." > build.txt
      - run:
          name: Build
          command: echo "Build << parameters.package_name >> ..."
      - persist_to_workspace:
          root: ~/project
          paths:
            - packages/<< parameters.package_name >>

  deploy:
    parameters:
      package_name:
        type: string

    executor: node
    working_directory: ~/project/packages/<< parameters.package_name >>

    steps:
      - attach_workspace:
          at: ~/project
      # This step is added to show that files are available from the build job.
      - run:
          name: Content to deploy
          command: ls && cat build.txt
      - deploy:
          name: Deploy
          command: echo "Deploying << parameters.package_name >> ..."

workflows:
  # Workflows defined for each package.

  api-to-stg:
    when: << pipeline.parameters.run-build-api-job >>
    jobs:
      - build:
          name: api-build
          package_name: api
          filters:
            branches:
              only: master
      - deploy:
          name: api-deploy
          package_name: api
          requires:
            - api-build

  app-to-stg:
    when: << pipeline.parameters.run-build-app-job >>
    jobs:
      - build:
          name: app-build
          package_name: app
          filters:
            branches:
              only: master
      - deploy:
          name: app-deploy
          package_name: app
          requires:
            - app-build

  auth-to-stg:
    when: << pipeline.parameters.run-build-auth-job >>
    jobs:
      - build:
          name: auth-build
          package_name: auth
          filters:
            branches:
              only: master
      - deploy:
          name: auth-deploy
          package_name: auth
          requires:
            - auth-build

  gateway-to-stg:
    when: << pipeline.parameters.run-build-gateway-job >>
    jobs:
      - build:
          name: gateway-build
          package_name: gateway
          filters:
            branches:
              only: master
      - deploy:
          name: gateway-deploy
          package_name: gateway
          requires:
            - gateway-build
  api-to-prod:
    when: << pipeline.parameters.run-build-api-job >>
    jobs:
      - build:
          name: api-build
          package_name: api
          filters:
            tags:
              only: /release-.*/
            branches:
              ignore: /.*/
      - deploy:
          name: api-deploy
          package_name: api
          requires:
            - api-build

  app-to-prod:
    when: << pipeline.parameters.run-build-app-job >>
    jobs:
      - build:
          name: app-build
          package_name: app
          filters:
            tags:
              only: /release-.*/
            branches:
              ignore: /.*/
      - deploy:
          name: app-deploy
          package_name: app
          requires:
            - app-build

  auth-to-prod:
    when: << pipeline.parameters.run-build-auth-job >>
    jobs:
      - build:
          name: auth-build
          package_name: auth
          filters:
            tags:
              only: /release-.*/
            branches:
              ignore: /.*/
      - deploy:
          name: auth-deploy
          package_name: auth
          requires:
            - auth-build

  gateway-to-prod:
    when: << pipeline.parameters.run-build-gateway-job >>
    jobs:
      - build:
          name: gateway-build
          package_name: gateway
          filters:
            tags:
              only: /release-.*/
            branches:
              ignore: /.*/
      - deploy:
          name: gateway-deploy
          package_name: gateway
          requires:
            - gateway-build
